import {
  Box,
  Container,
  CssBaseline,
  Toolbar,
  Typography,
} from '@mui/material';
import ThemeRegistry from '../ThemeRegistry';
import './global.css';
import AppBarStyled from './styles/AppBarSyled';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <CssBaseline />
        <Box component="body" sx={{ display: 'flex', height: '100vh' }}>
          <AppBarStyled position="fixed">
            <Container maxWidth="xl">
              <Toolbar>
                <Typography
                  variant="h4"
                  noWrap
                  component="a"
                  href="#app-bar-with-responsive-menu"
                  sx={{
                    display: { xs: 'none', md: 'flex' },

                    fontWeight: 700,

                    color: 'inherit',
                    textDecoration: 'none',
                  }}
                >
                  Massive Grocery
                </Typography>
              </Toolbar>
            </Container>
          </AppBarStyled>
          <Box component="main" sx={{ flexGrow: 1, p: 12, pt: 4 }}>
            <Toolbar />
            {children}
          </Box>
        </Box>
      </ThemeRegistry>
    </html>
  );
}
