GET http://localhost:3333/products/ HTTP/1.1

###

POST http://localhost:3333/products/create HTTP/1.1
content-type: application/json

{
    "name": "phonae",
    "brand": "Samsung"
}

###

PUT http://localhost:3333/products HTTP/1.1
content-type: application/json

{   "id":"5ed22e1a-1799-43b1-aa46-d99d65638f0a",
    "name": "How to use s",
    "brand": "Panachonik",
    "barcode": "102026873499"
}

###

DELETE http://localhost:3333/products HTTP/1.1
content-type: application/json

{   "id":"63595a65-2cdb-4a01-ba59-1c157a65d640"
    
}
